spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subs_db
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
server:
  port: 8080
springdoc:
  api-docs:
    enabled: true               # ???????? ??? ????????? ?????? ? ???????????? (?? ????????? ????????)
    path: /v3/api-docs           # ???? ??? JSON-???????????? OpenAPI (?? ????????? /v3/api-docs)
  swagger-ui:
    enabled: true                # ???????? Swagger UI (?? ????????? ????????)
    path: /swagger-ui             # ???? ??? ??????? ? Swagger UI (?? ????????? /swagger-ui)
    url: /v3/api-docs